name: Generate Sitemap

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url: 'https://jollygoodbridge.github.io'
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Generated sitemap.xml'
          add: 'sitemap.xml'
